// Code generated by protoc-gen-go. DO NOT EDIT.
// source: send_service.proto

package apis

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendParams struct {
	Contact              string   `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Priority             string   `protobuf:"bytes,4,opt,name=Priority,proto3" json:"Priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendParams) Reset()         { *m = SendParams{} }
func (m *SendParams) String() string { return proto.CompactTextString(m) }
func (*SendParams) ProtoMessage()    {}
func (*SendParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_46df95a7808dc814, []int{0}
}

func (m *SendParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendParams.Unmarshal(m, b)
}
func (m *SendParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendParams.Marshal(b, m, deterministic)
}
func (m *SendParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendParams.Merge(m, src)
}
func (m *SendParams) XXX_Size() int {
	return xxx_messageInfo_SendParams.Size(m)
}
func (m *SendParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SendParams.DiscardUnknown(m)
}

var xxx_messageInfo_SendParams proto.InternalMessageInfo

func (m *SendParams) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *SendParams) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SendParams) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SendParams) GetPriority() string {
	if m != nil {
		return m.Priority
	}
	return ""
}

type UpdateConfigParams struct {
	Configs              map[string]string `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateConfigParams) Reset()         { *m = UpdateConfigParams{} }
func (m *UpdateConfigParams) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigParams) ProtoMessage()    {}
func (*UpdateConfigParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_46df95a7808dc814, []int{1}
}

func (m *UpdateConfigParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigParams.Unmarshal(m, b)
}
func (m *UpdateConfigParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigParams.Marshal(b, m, deterministic)
}
func (m *UpdateConfigParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigParams.Merge(m, src)
}
func (m *UpdateConfigParams) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigParams.Size(m)
}
func (m *UpdateConfigParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigParams proto.InternalMessageInfo

func (m *UpdateConfigParams) GetConfigs() map[string]string {
	if m != nil {
		return m.Configs
	}
	return nil
}

type UseridByMobileParams struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseridByMobileParams) Reset()         { *m = UseridByMobileParams{} }
func (m *UseridByMobileParams) String() string { return proto.CompactTextString(m) }
func (*UseridByMobileParams) ProtoMessage()    {}
func (*UseridByMobileParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_46df95a7808dc814, []int{2}
}

func (m *UseridByMobileParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseridByMobileParams.Unmarshal(m, b)
}
func (m *UseridByMobileParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseridByMobileParams.Marshal(b, m, deterministic)
}
func (m *UseridByMobileParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseridByMobileParams.Merge(m, src)
}
func (m *UseridByMobileParams) XXX_Size() int {
	return xxx_messageInfo_UseridByMobileParams.Size(m)
}
func (m *UseridByMobileParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UseridByMobileParams.DiscardUnknown(m)
}

var xxx_messageInfo_UseridByMobileParams proto.InternalMessageInfo

func (m *UseridByMobileParams) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type BaseReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseReply) Reset()         { *m = BaseReply{} }
func (m *BaseReply) String() string { return proto.CompactTextString(m) }
func (*BaseReply) ProtoMessage()    {}
func (*BaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_46df95a7808dc814, []int{3}
}

func (m *BaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseReply.Unmarshal(m, b)
}
func (m *BaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseReply.Marshal(b, m, deterministic)
}
func (m *BaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseReply.Merge(m, src)
}
func (m *BaseReply) XXX_Size() int {
	return xxx_messageInfo_BaseReply.Size(m)
}
func (m *BaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_BaseReply proto.InternalMessageInfo

func (m *BaseReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *BaseReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UseridByMobileReply struct {
	Userid               string   `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseridByMobileReply) Reset()         { *m = UseridByMobileReply{} }
func (m *UseridByMobileReply) String() string { return proto.CompactTextString(m) }
func (*UseridByMobileReply) ProtoMessage()    {}
func (*UseridByMobileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_46df95a7808dc814, []int{4}
}

func (m *UseridByMobileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseridByMobileReply.Unmarshal(m, b)
}
func (m *UseridByMobileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseridByMobileReply.Marshal(b, m, deterministic)
}
func (m *UseridByMobileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseridByMobileReply.Merge(m, src)
}
func (m *UseridByMobileReply) XXX_Size() int {
	return xxx_messageInfo_UseridByMobileReply.Size(m)
}
func (m *UseridByMobileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UseridByMobileReply.DiscardUnknown(m)
}

var xxx_messageInfo_UseridByMobileReply proto.InternalMessageInfo

func (m *UseridByMobileReply) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func init() {
	proto.RegisterType((*SendParams)(nil), "apis.SendParams")
	proto.RegisterType((*UpdateConfigParams)(nil), "apis.UpdateConfigParams")
	proto.RegisterMapType((map[string]string)(nil), "apis.UpdateConfigParams.ConfigsEntry")
	proto.RegisterType((*UseridByMobileParams)(nil), "apis.UseridByMobileParams")
	proto.RegisterType((*BaseReply)(nil), "apis.BaseReply")
	proto.RegisterType((*UseridByMobileReply)(nil), "apis.UseridByMobileReply")
}

func init() { proto.RegisterFile("send_service.proto", fileDescriptor_46df95a7808dc814) }

var fileDescriptor_46df95a7808dc814 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x6a, 0xea, 0x40,
	0x14, 0xc7, 0x89, 0x7a, 0xbd, 0x7a, 0xae, 0xdc, 0xca, 0x54, 0x24, 0xcd, 0x4a, 0x02, 0x05, 0xbb,
	0x68, 0x16, 0x76, 0xd1, 0xd6, 0x4d, 0xa9, 0xa5, 0x74, 0x55, 0x90, 0x14, 0xd7, 0x65, 0x4c, 0x8e,
	0x61, 0xa8, 0xf9, 0x60, 0xce, 0x28, 0xe4, 0x31, 0xfa, 0x3a, 0x7d, 0xba, 0x32, 0x93, 0x49, 0x55,
	0xb4, 0xbb, 0xfc, 0xce, 0xe7, 0xff, 0xfc, 0x27, 0xc0, 0x08, 0xb3, 0xf8, 0x9d, 0x50, 0x6e, 0x45,
	0x84, 0x41, 0x21, 0x73, 0x95, 0xb3, 0x16, 0x2f, 0x04, 0xf9, 0x12, 0xe0, 0x0d, 0xb3, 0x78, 0xce,
	0x25, 0x4f, 0x89, 0xb9, 0xf0, 0x37, 0xca, 0x33, 0xc5, 0x23, 0xe5, 0x3a, 0x23, 0x67, 0xdc, 0x0d,
	0x6b, 0x64, 0x03, 0xf8, 0xa3, 0xf2, 0x42, 0x44, 0x6e, 0xc3, 0xc4, 0x2b, 0xd0, 0xf5, 0x29, 0x12,
	0xf1, 0x04, 0xdd, 0x66, 0x55, 0x6f, 0x91, 0x79, 0xd0, 0x99, 0x4b, 0x91, 0x4b, 0xa1, 0x4a, 0xb7,
	0x65, 0x52, 0x3f, 0xec, 0x7f, 0x3a, 0xc0, 0x16, 0x45, 0xcc, 0x15, 0x3e, 0xe5, 0xd9, 0x4a, 0x24,
	0x76, 0xf9, 0x83, 0x59, 0xbe, 0x12, 0x09, 0xb9, 0xce, 0xa8, 0x39, 0xfe, 0x37, 0xb9, 0x0c, 0xb4,
	0xc4, 0xe0, 0xb8, 0x34, 0xa8, 0x80, 0x9e, 0x33, 0x25, 0xcb, 0xb0, 0xee, 0xf2, 0xa6, 0xd0, 0xdb,
	0x4f, 0xb0, 0x3e, 0x34, 0x3f, 0xb0, 0xb4, 0x97, 0xe8, 0x4f, 0x7d, 0xc5, 0x96, 0xaf, 0x37, 0x58,
	0x5f, 0x61, 0x60, 0xda, 0xb8, 0x73, 0xfc, 0x00, 0x06, 0x0b, 0x42, 0x29, 0xe2, 0x59, 0xf9, 0x9a,
	0x2f, 0xc5, 0x1a, 0xad, 0xa8, 0x21, 0xb4, 0x53, 0xc3, 0x76, 0x8c, 0x25, 0xff, 0x16, 0xba, 0x33,
	0x4e, 0x18, 0x62, 0xb1, 0x2e, 0xb5, 0x0d, 0xb4, 0x89, 0x22, 0x24, 0x32, 0x55, 0x9d, 0xb0, 0x46,
	0x2d, 0x21, 0xa5, 0xc4, 0xae, 0xd3, 0x9f, 0xfe, 0x35, 0x9c, 0x1f, 0x2e, 0xaa, 0x46, 0x0c, 0xa1,
	0xbd, 0x31, 0xe1, 0x7a, 0x4f, 0x45, 0x93, 0x2f, 0x07, 0xba, 0xfa, 0x81, 0x1e, 0x13, 0xcc, 0x14,
	0xbb, 0x82, 0x96, 0x06, 0xd6, 0xaf, 0x9c, 0xd9, 0xbd, 0x9c, 0x77, 0x56, 0x45, 0x76, 0x9a, 0xee,
	0xa1, 0xb7, 0x6f, 0x1c, 0x73, 0x7f, 0x33, 0xf3, 0xb8, 0xf5, 0x05, 0xfe, 0x1f, 0x4a, 0x64, 0x9e,
	0x6d, 0x3e, 0xe1, 0x90, 0x77, 0x71, 0x2a, 0x67, 0x06, 0x2d, 0xdb, 0xe6, 0x4f, 0xbb, 0xf9, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x49, 0x9c, 0x53, 0x1a, 0x7f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SendAgentClient is the client API for SendAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SendAgentClient interface {
	Send(ctx context.Context, in *SendParams, opts ...grpc.CallOption) (*BaseReply, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigParams, opts ...grpc.CallOption) (*BaseReply, error)
	UseridByMobile(ctx context.Context, in *UseridByMobileParams, opts ...grpc.CallOption) (*UseridByMobileReply, error)
}

type sendAgentClient struct {
	cc *grpc.ClientConn
}

func NewSendAgentClient(cc *grpc.ClientConn) SendAgentClient {
	return &sendAgentClient{cc}
}

func (c *sendAgentClient) Send(ctx context.Context, in *SendParams, opts ...grpc.CallOption) (*BaseReply, error) {
	out := new(BaseReply)
	err := c.cc.Invoke(ctx, "/apis.SendAgent/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendAgentClient) UpdateConfig(ctx context.Context, in *UpdateConfigParams, opts ...grpc.CallOption) (*BaseReply, error) {
	out := new(BaseReply)
	err := c.cc.Invoke(ctx, "/apis.SendAgent/UpdateConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendAgentClient) UseridByMobile(ctx context.Context, in *UseridByMobileParams, opts ...grpc.CallOption) (*UseridByMobileReply, error) {
	out := new(UseridByMobileReply)
	err := c.cc.Invoke(ctx, "/apis.SendAgent/UseridByMobile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendAgentServer is the server API for SendAgent service.
type SendAgentServer interface {
	Send(context.Context, *SendParams) (*BaseReply, error)
	UpdateConfig(context.Context, *UpdateConfigParams) (*BaseReply, error)
	UseridByMobile(context.Context, *UseridByMobileParams) (*UseridByMobileReply, error)
}

// UnimplementedSendAgentServer can be embedded to have forward compatible implementations.
type UnimplementedSendAgentServer struct {
}

func (*UnimplementedSendAgentServer) Send(ctx context.Context, req *SendParams) (*BaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedSendAgentServer) UpdateConfig(ctx context.Context, req *UpdateConfigParams) (*BaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (*UnimplementedSendAgentServer) UseridByMobile(ctx context.Context, req *UseridByMobileParams) (*UseridByMobileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseridByMobile not implemented")
}

func RegisterSendAgentServer(s *grpc.Server, srv SendAgentServer) {
	s.RegisterService(&_SendAgent_serviceDesc, srv)
}

func _SendAgent_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendAgentServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.SendAgent/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendAgentServer).Send(ctx, req.(*SendParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SendAgent_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendAgentServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.SendAgent/UpdateConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendAgentServer).UpdateConfig(ctx, req.(*UpdateConfigParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SendAgent_UseridByMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseridByMobileParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendAgentServer).UseridByMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.SendAgent/UseridByMobile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendAgentServer).UseridByMobile(ctx, req.(*UseridByMobileParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _SendAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apis.SendAgent",
	HandlerType: (*SendAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _SendAgent_Send_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _SendAgent_UpdateConfig_Handler,
		},
		{
			MethodName: "UseridByMobile",
			Handler:    _SendAgent_UseridByMobile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "send_service.proto",
}
